[package]
name = "photomock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.4.3"
dioxus-desktop = "0.4.3"
dioxus-router = "0.4.3"
image = "0.24.7"
imageproc = "0.23.0"
